# In TypeScript actions, `dist/` is a special directory. When you reference
# an action with the `uses:` property, `dist/index.js` is the code that will be
# run. For this project, the `dist/index.js` file is transpiled from other
# source files. This workflow ensures the `dist/` directory contains the
# expected transpiled code.
#
# If this workflow is run from a feature branch, it will act as an additional CI
# check and fail if the checked-in `dist/` directory does not match what is
# expected from the build.
name: Build Transpiled JavaScript

on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  check-dist:
    name: Check dist/
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      - uses: DanTheMan827/config-git-user-action@v1
        with:
          user_name: ${{ github.actor }}

      - name: Commit changes
        run: |
          git add -Af dist/
          git commit -m "Build dist/" || exit 0
          git tag -f "dev/${{ github.ref_name }}"
          git push -f origin "dev/${{ github.ref_name }}"
